[tool.poetry]
name = "banking-transactions-app"
version = "0.1.0"
description = ""
authors = ["Oleg Matyushenko <mos_olma@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.3.3"
openpyxl = "^3.1.5"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
isort = "^7.0.0"
black = "^25.11.0"
mypy = "^1.18.2"


[tool.poetry.group.test.dependencies]
pytest = "^9.0.1"
pytest-cov = "^7.0.0"

[tool.isort]
line-length = 119

[tool.black]
line-length = 119
exclude = '''
/\.git/
'''

[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
exclude = "venv"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
